server {
    listen 80;
    server_name acikakademi.alperturkmen.com 206.189.97.102;

    root /var/www/react-app;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html; 
    }

    location /api {
        proxy_pass http://127.0.0.1:5002;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }

    location /files {
        proxy_pass http://127.0.0.1:5002/files/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

    }


    error_page 404 /index.html;

    gzip on;
    gzip_types text/css application/javascript text/javascript application/json application/xml text/plain;
    gzip_proxied any;
    gzip_min_length 1000;
}


